apiVersion: v1
kind: Pod
metadata:
    name: app
spec:
    containers:
        - name: container-app-loja
          image: rafanercessian/aplicacao-loja:v1
          ports: 
            - containerPort: 80
